### ISSUE TITLE
Add a expulsion evasion clause to Consequences

### ISSUE THREAD

**Issue by imsickofmaps** [zatech/code-of-conduct#10]
We expel people not Slack accounts from ZA Tech. We need to have explicit statement on how we will respond to people avoiding expulsion by creating secondary accounts.

**Comment by Vulcanit3** [comment]
With the only exception being an inappropriate username?
Since that's the only thing bound to an account and immutable

But there does need to be some security mechanism for persistent bans, otherwise bans are pointless and will just waste moderators time

**Comment by pjdelport** [comment]
Many CoC's have language that prohibits ban/suspension evasion, sockpuppet accounts, or similar obstruction of admin decisions. We could add something like this?

**Comment by pjdelport** [comment]
Straw proposal for addition to the list:

* Intentionally evading bans, suspensions, restrictions, or otherwise interfering with the admin team's decisions and actions
* Creating shell or sock puppet accounts to impersonate people, or evade bans

Comments?
