### ISSUE TITLE
Update code of conduct to have clear wording on piracy.

### ISSUE THREAD

**Issue by gee-forr** [zatech/code-of-conduct#15]
Hi,

With the recent posting of pirated books, perhaps we should update the CoC to either have a specific stance on piracy, or a general stance on illegal activity?

**Comment by frankkusel** [comment]
Hi.

I think pirated material should be explicitly forbidden.

**Comment by pjdelport** [comment]
To relay what I said on Slack:

> I think it's very fair to assume "Don't engage in or encourage illegal activities on this Slack" as a default.
> Regardless of one's individual stance on copyright reform, this is probably not the place to break the law as civil disobedience, unless ZA Tech as a whole wants to take an active and principled stake in that battle.

**Comment by n1c** [comment]
Closing this as stale. If there's something to be refreshed, please create a new [discussion](https://github.com/zatech/code-of-conduct/discussions).
