### ISSUE TITLE
Should there be a written stance on when messages can be deleted by admins?

### ISSUE THREAD

**Issue by n1c** [zatech/code-of-conduct#19]
There's been a few instances of people asking for admins to delete their messages.

Often it's a typo or some incorrect information; though sometimes there's a conversation & context that arises. We already don't allow people to edit the history too much with a short edit message time window, should we be deleting messages at all?

**Comment by zoidbergwill** [comment]
I've seen some communities have an "admin log" channel to store decisions, and we could put deleted logs in there or summaries of why they were deleted, depending on the message.

**Comment by n1c** [comment]
`zmeta-admin-message-deletes` exists as a private admin channel as the current solve to this.
