### ISSUE TITLE
Is there a generic stance on @channel'ing?

### ISSUE THREAD

**Issue by n1c** [zatech/code-of-conduct#2]

**Comment by jonathanendersby** [comment]
My vote would be that nothing is so important (or at least should not be) on the ZATech chat that justifies @channeling. Yes, users can disable receiving the notifications, but the default behaviour should be the most sane setting. Unfortunately with a large group of people you can't bank on rational behaviour and many people incorrectly view their personal cause-du-jour as important enough to bother the larger group. The reality is that most people will never use @channel, but when it is used by a misinformed individual they will be annoying an increasingly large number of people.
