### ISSUE TITLE
Should we allow everyone to edit the custom emojis?

### ISSUE THREAD

**Issue by n1c** [zatech/code-of-conduct#20]
As the community grows it becomes harder and harder to trust that all the content, interactions etc. are in good faith. While the burden of whatever does happen on the platform will always sit with “the admins” and at the end of the day, me personally.

The ability for anyone to upload custom emojis has in the past had a few instances of bad behaviour. Emojis of members of the community have been added without consent, emojis co-opted as symbols for hate groups and other images some groups find harmful have been added.

Personally it’s an easy decision for me to make that the group does not _need_ such a massive free for all collection of emojis. When balancing it against the issues it has and has potential to cause I’m in favour of removing all the currently added custom emojis, locking down the ability for anyone to add and taking requests for custom emojis to be added when they have some useful impact. For example having the OfferZen, Make, Travelstart etc. branding as an emoji is useful to those communities.

**Comment by zoidbergwill** [comment]
While disabling anyone being able to create emojis would increase the burden on admins, I'm happy to deal with that. I can imagine there'll be a spike of suggested emojis if we purge them all, but after that I think it'll be pretty low overhead. Lower than the event announcements.

**Comment by ksmit** [comment]
with this being implemented today I suppose this issue can then be closed. Is it then safe to assume that we can request emojis be added in #asktheadmins or should we dm @zoidbergwill?

**Comment by n1c** [comment]
You can message #asktheadmins

**Comment by Vulcanit3** [comment]
So to clarify. There now needs to be justification for each emoji request?

What is deemed to be a valid reason for an emoji?

**Comment by n1c** [comment]
I'm going to close this issue as it's already been haphazardly implemented, and discussion going forward will happen elsewhere (#26 etc.)
