### ISSUE TITLE
Strategy for supporting custom emoji going forward

### ISSUE THREAD

**Issue by n1c** [zatech/code-of-conduct#26]
Following on from the previous discussion about custom emoji: https://github.com/zatech/code-of-conduct/issues/20 we're currently in an awkward in-between state. A bunch of custom emoji have been removed while some remain.

During the initial purge some emojis got kept because they're brands (:offerzen:, :gettruck: etc.), some got kept because of general popularity and a whole bunch got kept because behind the scenes my delete requests were 429ing and I didn't know.

The current plan going forward is to nuke _all_ custom emojis (next week?), allow for a cooling off period (a few weeks?) and then add back custom emojis on request.

After the cooling off period requests can be made in #zmeta-emoji, please include the image you'd like along with the associated :emojiname: whilst being aware of Slack's.

We'll need to work out some heuristics for what is "allowed" in the sense of is it offensive? Is it useful? Is it already covered? etc.

**Comment by n1c** [comment]
Cool suggestion re: repository+prs+bot by Cobus here: https://zatech.slack.com/archives/C03A23LKM/p1567605275189700?thread_ts=1567595178.159900&cid=C03A23LKM

**Comment by seagyn** [comment]
Can we not just keep all the brand logos? I don't see why they would need to get removed.

**Comment by catonice** [comment]
I say keep the brands, keep the slack approved custom emojis - like party parrots - chuck anything that doesn't fit the bill out and then get requests - I do agree similar emojis are clutter - aka 5 different suspicious emojis

**Comment by andrewjrhill** [comment]
Surely it's quicker and easier to ban the few members who have added hateful emojis than it is to police the entire communities requests for custom emojis.

**Comment by n1c** [comment]
Closing this as stale. If there's something to be refreshed, please create a new [discussion](https://github.com/zatech/code-of-conduct/discussions).
