### ISSUE TITLE
Should we be specific on how often you can repost #jobpostings positions?

### ISSUE THREAD

**Issue by n1c** [zatech/code-of-conduct#3]

**Comment by zoidbergwill** [comment]
:+1:

I saw someone post two days in a row, and I think that's a bit much, since anyone desperately looking for a job is gonna be looking at it regularly, and would probably go about a week or so back in history. I can currently go back 11 days, so a weekly post would be decent, I think.

**Comment by n1c** [comment]
Closing this as stale. If there's something to be refreshed, please create a new [discussion](https://github.com/zatech/code-of-conduct/discussions).
